lzc-sdk-version: "0.1"
name: Pastefy
package: cloud.lazycat.app.pastefy
version: 7.0.3
description: pasty
homepage: https://github.com/interaapps/pastefy
author: interaapps
application:
  subdomain: pastefy
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  routes:
    - /=http://pastefy:80/
services:
    
  pastefy-db:
    container_name: pastefy-db
    image:  registry.lazycat.cloud/czyt/library/mariadb:a34fe8871205a8fd
    environment:
      - MYSQL_ROOT_PASSWORD=pastefy
      - MYSQL_DATABASE=pastefy
      - MYSQL_USER=pastefy
      - MYSQL_PASSWORD=pastefy
    binds:
      - /lzcapp/var/db:/var/lib/mysql
    health_check:
      test:
        - CMD-SHELL
        - healthcheck.sh --connect --innodb_initialized
      start_period: 60s
      
  pastefy:
    image: docker.hlmirror.com/interaapps/pastefy:latest
    environment:
      - HTTP_SERVER_PORT=80
      - HTTP_SERVER_CORS=*
      - DATABASE_DRIVER=mysql
      - DATABASE_NAME=pastefy
      - DATABASE_USER=pastefy
      - DATABASE_PASSWORD=pastefy
      - DATABASE_HOST=pastefy-db
      - DATABASE_PORT=3306
      - SERVER_NAME=https://${LAZYCAT_APP_DOMAIN}
      - OAUTH2_PROVIDER_CLIENT_ID=null
      - OAUTH2_PROVIDER_CLIENT_SECRET=null
    depends_on:
      - pastefy-db
